spring:
  application:
    name: Demo1
  datasource:
    port: 5432
    url: jdbc:postgresql://localhost:5432/demo_1
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maxLifetime: 900000
      maximumPoolSize: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: book_store
    schemas:
      - book_store
logging:
  level:
    org.flywaydb: DEBUG

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: book_store
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl